services:
    mysql:
        image: mysql:8.3.0
        environment:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3306:3306"
        volumes:
          - ./data/mysql:/var/lib/mysql
          - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
